name: basic-ci

on: push

jobs:
  ci:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: lint
        run: npm run lint
      - name: ts
        run: npm run ts:check
      - name: test
        run: npm run test
      - name: prettier
        run: npm run format -- --check
      - name: compile
        run: npm run compile
      - name: count
        run: |
          export NUM_REPOS=$(node -e 'require("${{ github.workspace }}/dist/index.js").data().then(rs => process.stdout.write(rs.length+""))');
          test $NUM_REPOS -gt 100
      - name: clone
        run: |
          node -e 'require("${{ github.workspace }}/dist/index.js").cloneAll("${{ github.workspace }}")';
          test -d ${{ github.workspace }}/en/ambrose-rigge && test -d ${{ github.workspace }}/es/william-penn
